<?php
/**
 * Queue Monitor page.
 *
 * Provides a read-only view of recent tasks in the queue with the ability to
 * retry or delete (cancel) failed tasks. Actions are protected by
 * capability checks, nonces and POST requests to mitigate CSRF.
 *
 * This page is intended for administrative users with the `manage_options`
 * capability. It reuses the TaskQueue service used elsewhere in the plugin
 * rather than relying on a missing or legacy class.
 */

declare(strict_types=1);

use SEOJusAI\Tasks\TaskQueue;

defined('ABSPATH') || exit;

// Restrict access to administrators.
if ( ! current_user_can('manage_options') ) {
    wp_die(esc_html__('Недостатньо прав доступу.', 'seojusai'));
}

// Prepare a notice for user feedback after an action.
$notice = '';

// Handle queue actions submitted via POST.
if (isset($_POST['seojusai_queue_action'], $_POST['task_id'])) {
    // Verify nonce before executing any state change.
    check_admin_referer('seojusai_queue_action');

    $action = sanitize_key((string) $_POST['seojusai_queue_action']);
    $task_id = (int) $_POST['task_id'];

    if ($task_id > 0) {
        $queue = new TaskQueue();
        if ($action === 'retry') {
            // Immediately requeue the task for retry.
            $queue->retry_now($task_id);
            $notice = '<div class="notice notice-success is-dismissible"><p>' . esc_html__('Задачу повторно поставлено в чергу.', 'seojusai') . '</p></div>';
        } elseif ($action === 'delete' || $action === 'cancel') {
            // Delete/cancel the task from the queue.
            $queue->delete($task_id);
            $notice = '<div class="notice notice-success is-dismissible"><p>' . esc_html__('Задачу видалено.', 'seojusai') . '</p></div>';
        }
    }
}

// Fetch a list of tasks to display. Limit to 50 for performance.
$queue = new TaskQueue();
$items = $queue->list(50, 0, '');

?>
<div class="wrap">
    <h1><?php esc_html_e('SEOJusAI — Монітор черги', 'seojusai'); ?></h1>

    <?php
    // Output any notice generated by a user action.
    if ($notice !== '') {
        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
        echo $notice;
    }
    ?>

    <table class="widefat striped">
        <thead>
            <tr>
                <th style="width:80px;"><?php esc_html_e('ID', 'seojusai'); ?></th>
                <th><?php esc_html_e('Дія', 'seojusai'); ?></th>
                <th style="width:110px;"><?php esc_html_e('Статус', 'seojusai'); ?></th>
                <th style="width:90px;"><?php esc_html_e('Спроби', 'seojusai'); ?></th>
                <th style="width:180px;"><?php esc_html_e('Оновлено', 'seojusai'); ?></th>
                <th style="width:160px;"><?php esc_html_e('Дії', 'seojusai'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($items)): ?>
                <tr><td colspan="6"><?php esc_html_e('Немає задач.', 'seojusai'); ?></td></tr>
            <?php else: ?>
                <?php foreach ($items as $task): ?>
                    <?php
                        // Ensure the row is an associative array as returned by TaskQueue::list().
                        $tid      = (int) ($task['id'] ?? 0);
                        $action   = (string) ($task['action'] ?? '');
                        $status   = (string) ($task['status'] ?? '');
                        $attempts = (int) ($task['attempts'] ?? 0);
                        $max      = (int) ($task['max_attempts'] ?? 0);
                        $updated  = (string) ($task['updated_at'] ?? '');
                    ?>
                    <tr>
                        <td><?php echo $tid; ?></td>
                        <td><code><?php echo esc_html($action); ?></code></td>
                        <td><?php echo esc_html($status); ?></td>
                        <td><?php echo $attempts . ' / ' . $max; ?></td>
                        <td><?php echo esc_html($updated); ?></td>
                        <td>
                            <form method="post" style="display:inline;">
                                <?php wp_nonce_field('seojusai_queue_action'); ?>
                                <input type="hidden" name="task_id" value="<?php echo $tid; ?>" />
                                <?php if ($status === 'failed'): ?>
                                    <button class="button" type="submit" name="seojusai_queue_action" value="retry">
                                        <?php esc_html_e('Повторити', 'seojusai'); ?>
                                    </button>
                                <?php endif; ?>
                                <button class="button button-link-delete" type="submit" name="seojusai_queue_action" value="delete" onclick="return confirm('<?php echo esc_js(__('Видалити задачу?', 'seojusai')); ?>');">
                                    <?php esc_html_e('Скасувати', 'seojusai'); ?>
                                </button>
                            </form>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
</div>